### ISSUE TITLE
racer v2.1.27 fails to compile with rustc v1.40.0-nightly (787005079 2019-10-04)

### ISSUE THREAD

**Issue by xttjsn** [racer-rust/racer#1075]
I first installed nightly rust via:
```
rustup toolchain add nightly
```

Then I tried to build racer via:
```
cargo +nightly install racer
```

```
error[E0046]: not all trait items implemented, missing: `mixed_site`
   --> /home/xtt/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-syntax-583.0.0/ext/proc_macro_server.rs:657:1
    |
657 | impl server::Span for Rustc<'_> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `mixed_site` in implementation
    |
    = note: `mixed_site` from trait: `fn(&mut Self) -> <Self as proc_macro::bridge::server::Types>::Span`

   Compiling racer-cargo-metadata v0.1.1
error: aborting due to previous error
```

Host:
```Linux fedora-30 5.1.18-300.fc30.x86_64 #1 SMP Mon Jul 15 15:42:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by xttjsn** [comment]
Duplicate with #1074.
