### ISSUE TITLE
Cargo build fails on Mac OS

### ISSUE THREAD

**Issue by arun11299** [racer-rust/racer#835]
Commit:
```
commit 86be1103e804bae2d0c324a94984abe3e12a3db5
Merge: cff609a cb18f5f
Author: Joe Wilm <jwilm@users.noreply.github.com>
Date:   Mon Mar 19 17:17:56 2018 -0700

    Merge pull request #834 from Eijebong/bump

    Bump log, env_logger, lazy_static and run a full cargo update
```

Error:
```
warning: unused import: `iter`
  --> src/racer/nameres.rs:16:22
   |
16 | use std::{self, vec, iter};
   |                      ^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0277]: the trait bound `std::option::Option<u8>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:187:24
    |
187 |         let cur_byte = self.cur_byte()?;
    |                        ----------------
    |                        |
    |                        the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                        in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<u8>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<(char, usize)>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:187:24
    |
187 |         let cur_byte = self.cur_byte()?;
    |                        ----------------
    |                        |
    |                        the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                        in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(char, usize)>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `std::option::Option<u8>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:198:31
    |
198 |                         Some((self.cur_byte()? as char, self.pos - 1))
    |                               ----------------
    |                               |
    |                               the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                               in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<u8>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<(char, usize)>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:198:31
    |
198 |                         Some((self.cur_byte()? as char, self.pos - 1))
    |                               ----------------
    |                               |
    |                               the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                               in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(char, usize)>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `std::option::Option<u8>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:218:24
    |
218 |         let cur_byte = self.cur_byte()?;
    |                        ----------------
    |                        |
    |                        the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                        in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<u8>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<(char, usize)>: std::ops::Try` is not satisfied
   --> src/racer/codecleaner.rs:218:24
    |
218 |         let cur_byte = self.cur_byte()?;
    |                        ----------------
    |                        |
    |                        the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                        in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(char, usize)>`
    = note: required by `std::ops::Try::from_error`

error: aborting due to 6 previous errors

error: Could not compile `racer`.
```

Platform : Mac OS Yosemite 10.10.5 (14F1713)

**Comment by kngwyu** [comment]
Please note the output of
`rustc -v`

**Comment by arun11299** [comment]
Hi @kngwyu 

```
ArunMu:~ amuralid$ rustc --version
rustc 1.21.0 (3b72af97e 2017-10-09)
```

Thanks. It works with 1.24 version.
